artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: dataset/ML/data/ocr
  cleaned_dataset: artifacts/data_ingestion/data

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  required_files_list: ["train.csv", "test.csv"]
  required_files_path: artifacts/data_ingestion/data

data_transformation:
  root_dir: artifacts/data_transformation
  ingested_train_csv_file_path: artifacts/data_ingestion/data/train.csv
